### PR TITLE
Initialize GO module

### PR DESCRIPTION
**Pull request by metarsit-nutonomy**
# Issue #13 

## Changes
- Initialize GO module

## Command I ran:
```
$ go mod init github.com/rticommunity/rticonnextdds-connector-go
$ go mid tidy
```

### CODE REVIEW

**Comment by kyoungho** [comment]
I still have an issue when using go modules because it does not download actual library files. Did you figure out the issue?

**Comment by metarsit-nutonomy** [comment]
can you try check out my branch and run:

> go mod download

it seems to work for me now

**Comment by kyoungho** [comment]
Ah yes, the go module for this repository is working. But if this module is used by another repository via go module, it still seems not working because the library files are not fully downloaded. I will merge and close this. Thanks!

**Comment by metarsit-nutonomy** [comment]
@kyoungho so we have to start tagging :)

**Comment by kyoungho** [comment]
@metarsit-nutonomy Got it. Tagging would be useful if this repo by another repo as a module with go module. Have you made it working? When I tried to do, it still does not work.  

What I did:
1. copy a simple example to a new directory
2. go mod init
3. go test

It failed because go module did not download library files...

```go: downloading github.com/metarsit-nutonomy/rticonnextdds-connector-go v0.0.0-20200503001816-9980263f1d41
# github.com/metarsit-nutonomy/rticonnextdds-connector-go
/usr/bin/ld:/home/kyoungho/go/pkg/mod/github.com/metarsit-nutonomy/rticonnextdds-connector-go@v0.0.0-20200503001816-9980263f1d41/rticonnextdds-connector/lib/x64Linux2.6gcc4.4.5/librtiddsconnector.so: file format not recognized; treating as linker script
/usr/bin/ld:/home/kyoungho/go/pkg/mod/github.com/metarsit-nutonomy/rticonnextdds-connector-go@v0.0.0-20200503001816-9980263f1d41/rticonnextdds-connector/lib/x64Linux2.6gcc4.4.5/librtiddsconnector.so:1: syntax error
collect2: error: ld returned 1 exit status

**Comment by metarsit-nutonomy** [comment]
can you share with me your output of `go env`?

**Comment by metarsit-nutonomy** [comment]
go mod only download go files :)

**Comment by kyoungho** [comment]
Right. That would be an issue when someone uses go module and use Go Connector as one of their modules. But it is still useful to use go module for this repo to manage dependencies. Thanks again for this.

**Comment by metarsit-nutonomy** [comment]
:) 

I think with the configuration of CGO environment variable and having the dynamic lib the right place will solve the problem. I have it configured on my workspace :)

**Comment by kyoungho** [comment]
Yes, we could work around that way. It will be nice if we can figure out to make go module automatically download the library files as well. Please share with us if you find a way to do it. Thanks.

**Comment by tom-wp** [comment]
I ran into this same issue.  To correctly download the library files you need to make sure you have Git LFS installed:

https://git-lfs.github.com/

Then you need to set the go environment variable to not use the proxy for this repo:

```
go env -w GOPRIVATE="github.com/rticommunity/*"
```

Appending this to any existing private repos you already have.  This can be seen with `go env`.

**Pull request merged**
